### ISSUE TITLE
报一个bug吧，不能白用你的东西

### ISSUE THREAD

**Issue by Cwmmm** [leiyong0326/UoocAutoPlay#1]
你的匹配路径有问题，搞得我的自己测试改路径，

// @match *://www.uooconline.com/home/learn/index*

原先的路径不能用哦

**Comment by Cwmmm** [comment]
那个前后要加*

**Comment by leiyong0326** [comment]
> 你的匹配路径有问题，搞得我的自己测试改路径，
> 
> // @match _://www.uooconline.com/home/learn/index_
> 
> 原先的路径不能用哦

好吧,谢谢.那我改一下,很久没用了..
